# Site settings
title: Arte y Oficio Plataforma
email: arteyoficio.plataforma@gmail.com
description: >
  Arte y Oficio es un espacio que ofrece una extensión educativa para la Cultura y las Artes en Culiacán, Sinaloa. También gestiona proyectos culturales.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.arteyoficio.mx" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
